version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "topic: dependencies"
      - "type: maintenance"
    commit_message:
      prefix: "chore"
      include_scope: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "topic: dependencies"
      - "type: maintenance"
    commit_message:
      prefix: "chore"
      include_scope: true
