version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'topic: dependencies'
      - 'type: maintenance'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'topic: dependencies'
      - 'type: maintenance'
