[package]
name = "db"
version = "0.1.0"
authors = ["Louis Birla <louis.birla@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
log = "0.4.13"
