[package]
name = "block-types"
version = "0.0.1"
authors = ["Louis Birla <louis.birla@gmail.com>"]
edition = "2018"

[dependencies]
block-tools = { path = "../block-tools" }
serde = "1.0.126"
serde_json = "1.0.75"
log = "0.4.14"
