name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: 'pascalgn/automerge-action@c6f2699cc4c19ea7ce7f560dbebd85565b744377'
        env:
          GITHUB_TOKEN: '${{ secrets.AUTOTHINGS_TOKEN }}'
          MERGE_FORKS: 'false'
          MERGE_REMOVE_LABELS: 'automerge'
