name: Introspection

on: [push]

env:
  INTROSPECTING: "true"

jobs:
  check:
    name: Graphql Checking
    runs-on: ubuntu-latest
    steps:
      - name: Auto-cancel redundant jobs
        uses: technote-space/auto-cancel-redundant-job@v1

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "14"

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - run: yarn add graphql @graphql-inspector/cli

      - name: Introspect schema
        run: |
          cargo run &
          npx wait-on http-get://localhost:4000/ &&
          yarn graphql-inspector introspect http://localhost:4000 --write schema.graphql &&
          kill $!

      - uses: kamilkisiela/graphql-inspector@master
        if: ${{ !contains(github.ref, 'dependabot') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: "schema.graphql"
          endpoint: "https://api.loop.page/"
          annotations: true
