name: Lint
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-cancel redundant jobs
        uses: technote-space/auto-cancel-redundant-job@v1

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.AUTOTHINGS_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Basic checks
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Advanced Clippy checks
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Check if there are changes in formatting
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Fail if formatting is off
        if: steps.changes.outputs.changed == 1
        run: exit 1
