name: Migrations

on:
  push:
    branches:
      - main

env:
  DATABASE_URL: ${{ secrets.PROD_DB_URL }}
jobs:
  migrate:
    name: Migrate DB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - run: apt install libpq-dev
      - run: cargo install diesel_cli --no-default-features --features "postgres"
      - run: cd block-tools && diesel migration run
