on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
name: Suite
env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/testing
  SESSION_SECRET: 1234567890qwertyuiopasdfghjklzxcvbnm
  SMTP_SERVER: TESTING_SMTP_SERVER
  SMTP_USERNAME: TESTING_SMTP_USERNAME
  SMTP_PASSWORD: TESTING_SMTP_PASSWORD
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      ## Checkout & Rust
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Load bins
        uses: actions/download-artifact@v2
        with:
          name: bin
          path: ~/.cargo/bin
          required: false

      - name: Check if bins were loaded
        id: bins_exist
        uses: andstor/file-existence-action@v1
        with:
          files: ~/.cargo/bin/diesel

      ## Diesel
      - name: Install diesel cli
        if: steps.bins_exist.outputs.files_exists != 'true'
        run: sudo apt install libpq-dev && cargo install diesel_cli --no-default-features --features "postgres"

      ## Tarpaulin
      - name: Install tarpaulin
        if: steps.bins_exist.outputs.files_exists != 'true'
        run: cargo install cargo-tarpaulin

      - name: Load target
        uses: actions/download-artifact@v2
        with:
          name: target-${{ hashFiles('**/Cargo.lock') }}
          path: target
          required: false

      - name: Check if target was loaded
        id: target_exist
        uses: andstor/file-existence-action@v1
        with:
          files: target/loaded

      ## Load target cache
      - name: Install target
        if: steps.target_exist.outputs.files_exists != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: check

      ## Upload build artifacts
      - name: Upload binaries
        if: steps.bins_exist.outputs.files_exists != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: ~/.cargo/bin
      - name: Upload target
        if: steps.target_exist.outputs.files_exists != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: target--${{ hashFiles('**/Cargo.lock') }}
          path: target
  test:
    runs-on: ubuntu-latest
    needs: setup
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Load target
        uses: actions/download-artifact@v2
        with:
          name: target-${{ hashFiles('**/Cargo.lock') }}
          path: target

      - name: Allow access
        run: sudo chown -R $(whoami) ./target

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Load bins
        uses: actions/download-artifact@v2
        with:
          name: bin
          path: ~/.cargo/bin

      - name: Allow access
        run: sudo chown -R $(whoami) ~/.cargo

      - name: Setup DB
        run: cd block-tools && diesel setup && diesel migration run

      - name: Test & Coverage
        run: cargo tarpaulin --out Xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Load target
        uses: actions/download-artifact@v2
        with:
          name: target-${{ hashFiles('**/Cargo.lock') }}
          path: target

      - name: Allow access
        run: sudo chown -R $(whoami) ./target

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Basic checks
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Check formatting
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Fail if formatting is off
        if: steps.changes.outputs.changed == 1
        run: exit 1
