on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
name: Tests
jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
      - name: Install dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
