on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
name: Tests
env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/testing
  SESSION_SECRET: 1234567890qwertyuiopasdfghjklzxcvbnm
  SMTP_SERVER: TESTING_SMTP_SERVER
  SMTP_USERNAME: TESTING_SMTP_USERNAME
  SMTP_PASSWORD: TESTING_SMTP_PASSWORD
jobs:
  full:
    runs-on: ubuntu-latest
    container:  louisbirla/apitestci
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.AUTOTHINGS_TOKEN }}
          submodules: true

      - name: Setup DB
        run: cd block-tools && diesel setup && diesel migration run

      - name: Test + Generate code coverage
        run: cargo tarpaulin --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
